// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxkqtdugftnbvywerzri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4a3F0ZHVnZnRuYnZ5d2VyenJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjQ4NDcsImV4cCI6MjA2Mzk0MDg0N30.rOff4eLNYsidkmVzeZIcujgLHFr6tazC1B8PIYSqLJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);