FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app files
COPY . .

# Expose Vite port
EXPOSE 8080

# Start dev server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
